cc_proto_library(
    name = "onnx_cc_proto",
    deps = [
        ":onnx_proto"
    ],
    visibility = ["//visibility:public"],
)

proto_library(
    name = "onnx_proto",
    srcs = glob(["*.proto"]),
)
